### ISSUE TITLE
Feature: domain name compatible slug (no underscores)

### ISSUE THREAD

**Issue by nkuehn** [rlespinasse/github-slug-action#103]
**Is your feature request related to a problem? Please describe.**
We're using the slug action to generate preview site URLs from git branch names.  The slug is used as a subdomain (or sub-subdomain) pointing to the respective deployment.  
We naively thought that the SLUG_URL slugs are good for that but realized the hard way that the hostname part of the DNS name cannot generally have underscores.  It's a bit messy ( https://en.wikipedia.org/wiki/Hostname#Syntax ) but I conclude that it's at least not a safe assumption (and did in fact not work in our case).

**Describe the solution you'd like**
Either 
 * change the behavior of `SLUG_URL` (because a "URL" contains a "hostname" as a part and assuming you can use that slug anywhere in a full URL is not correct).  But that would be a breaking change. 
 * find some other means of supporting the use case. Extra exclusion characters configurable? Yet another set of variables like `SLUG_HOSTNAME`?  

All 

**Describe alternatives you've considered**
 * dropping this action for a custom script (not ideal, needs to be maintained too)
 * tolerating the error somehow (currently not possible, it's wrapped into other actions)

**Additional context**
I'm sorry to come up with yet another feature request...

**Comment by rlespinasse** [comment]
@nkuehn thanks for contributing with this new feature request, and with extensive details 👏 

`SLUG_URL` is meant to be safe for URL, so we need to drop the underscore as well. This means is not a feature but a bug.

**Comment by nkuehn** [comment]
Thank you  for the fast feeback!  If you are out of time capacity I can try ask someone from our team to contribute.

**Comment by rlespinasse** [comment]
@nkuehn Thanks for the contribution offering, nice to hear. I have already worked on this fix, maybe the next one or the next feature.

After analysis, in this case, the documentation does not take into account the need to remove the underscore on SLUG_URL for the v3 and v4 series, but the implementation removes it only for the v3. It's a documentation bug for the v3 and a migration bug for the v4.
