### ISSUE TITLE
Bug: `SLUG_URL` can end with a hyphen

### ISSUE THREAD

**Issue by timonrey** [rlespinasse/github-slug-action#109]
**Describe the bug**
We're using the slug action to generate preview site URLs from git branch names. The slug is used as a subdomain (or sub-subdomain) pointing to the respective deployment. That works pretty well, mainly thanks to your quick response [the last time](https://github.com/rlespinasse/github-slug-action/issues/103). Thank you again for that! 🙌🏼 
But now we ran into another issue.
We are using the `SLUG_URL` to create the subdomain and `slug-maxlength` to adjust the length of the slug to our needs.
We noticed that sometimes, when our branch name is too long and the slug length is being adjusted (or trimmed to the right length) that it can happen that the slug url is ending with an hyphen, which is not a valid hostname in the URL. That gives us an error when we try to create the subdomains.
If I understand the documentation correctly, the trailing `-` should be removed from the slug. But I guess this is not covered when using the `slug-maxlength` configuration. 🤔

**To Reproduce**
- Use a long string with hyphens in between words.
- Use SLUG_URL with slug-maxlength to create a slug out of the string that is shorter than the original string
- Try to find the right length of either the string or the maxlength to truncate the string that it ends with an hyphen

**Expected behavior**
The SLUG_URL should never end with a hyphen.

**Screenshots**
As you can see, we tried to use the SLUG_URL (our branch name) as subdomain. And in this particular case, the branch name was truncated to the configured length and ended with a hyphen.
![image (1)](https://user-images.githubusercontent.com/31767369/173803257-7d925ac4-0dbb-4dd8-8946-d2fbb31a9c63.png)

**Additional context**
Thank you very much for the quick support you gave us so far! We hope we can help you with this contribution :)

**Comment by timonrey** [comment]
So I assume you only need to do step 3d and 4d after shortening the length again:
https://github.com/rlespinasse/slugify-value/blob/v1.x/slugify.sh#L39-L54

**Comment by nkuehn** [comment]
PS: it's not vercel specific, that is just our hosting provider today.  The constraint to not have a hyphen at the end is generic in the DNS spec :  https://en.wikipedia.org/wiki/Hostname#Syntax

**Comment by rlespinasse** [comment]
![image](https://user-images.githubusercontent.com/1280212/173841686-f922e4f0-36bb-41c5-b875-9d9ea639723b.png)

**Comment by rlespinasse** [comment]
@timonrey the 4d step is now plan to be done after the reduce to be compliant with the slug definition and the DNS spec

**Comment by rlespinasse** [comment]
@timonrey @nkuehn this new release should do

**Comment by timonrey** [comment]
@rlespinasse Thank you for the quick fix! 🙌🏼
