### ISSUE TITLE
Do not replace periods with dashes

### ISSUE THREAD

**Issue by onedr0p** [rlespinasse/github-slug-action#11]
I am trying to use this action with building version tags. Using this action when I create a tag e.g. `v3.0.0` this variable `GITHUB_REF_SLUG` will be `v3-0-0`.

My suggestion is to don't replace periods or create a new environment variable that we can use for tags.

**Comment by rlespinasse** [comment]
Good catch

**Comment by rlespinasse** [comment]
This is now available on the 2.0.0 version of this action
