### ISSUE TITLE
Error on GitHub Enterprise Server 3.6.2 since github-slug-action@v4.3.1

### ISSUE THREAD

**Issue by kadero** [rlespinasse/github-slug-action#121]
Hello :wave:,

**Describe the bug**
We've got an error since github-slug-action@v4.3.1  on GitHub Enterprise Server 3.6.2:

Here are the logs:
```
Run rlespinasse/github-slug-action@v4
  with:
    prefix: SL_SH_
    slug-maxlength: 6[3](https://git.epo.org/ds/cv-pipelines/runs/52955?check_suite_focus=true#step:4:3)
Run $GITHUB_ACTION_PATH/preflight.sh
  $GITHUB_ACTION_PATH/preflight.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail ***0***
  env:
    INPUT_SLUG_MAXLENGTH: 63
    INPUT_SHORT_LENGTH: 
/runner/_work/_actions/rlespinasse/github-slug-action/v[4](https://git.epo.org/ds/cv-pipelines/runs/52955?check_suite_focus=true#step:4:4)/preflight.sh: line 34: : No such file or directory
```

Seems that it's linked to the update to use GITHUB_OUTPUT:
https://github.com/rlespinasse/github-slug-action/pull/117/files
Why this update was needed ?

It's working well if we pin github-slug-action@v4.3.0.

Thanks for your help :pray:

**Comment by rlespinasse** [comment]
@kadero It's linked to #118, I reopen the issue to support it.

Thanks for the report.

**Comment by rlespinasse** [comment]
Only the v4 versions are impacted since the v3 versions use the `@actions/toolkit` js library (which correctly manage the GHES runner)

**Comment by rlespinasse** [comment]
@kadero the new version `v4.4.0` resolves your bug?

**Comment by kadero** [comment]
Hello @rlespinass :wave:,

Yes it's working like a charm !

Thanks for the work done :slightly_frowning_face:, we can close this issue !

:pray:

**Comment by rlespinasse** [comment]
@kadero thanks
