### ISSUE TITLE
Other operating systems support

### ISSUE THREAD

**Issue by aminya** [rlespinasse/github-slug-action#16]
What dependency this is using that prevents it from running on other operating systems?

**Comment by rlespinasse** [comment]
Currently, the Github actions system don't support running `Container-based` action on Windows or Macos. 
Error when using it on a platform other than Linux : `##[error]Container action is only supported on Linux`.

To support others systems, the action may need a complete rewrite.
What is your current need?

**Comment by rlespinasse** [comment]
Thanks to @Ameausoone a pull request #23 is currently in review to enable a windows or macos workflow to use this action.

**Comment by rlespinasse** [comment]
See https://github.com/rlespinasse/github-slug-action/blob/v2.x/README.md#cant-run-on-windows-or-macos

**Comment by aminya** [comment]
Thank you so much! It would be nice if you make 3.x the default version in the readme.

**Comment by rlespinasse** [comment]
@aminya this v3.x will become the default one and the release automation will be activated after an incubation period to be sure nothing is broken since the rewrite.
