### ISSUE TITLE
GITHUB_SHA different value for PR events

### ISSUE THREAD

**Issue by MadJlzz** [rlespinasse/github-slug-action#45]
**Is your feature request related to a problem? Please describe.**

Actually, GitHub is changing the value of `GITHUB_SHA` for pull request events that refers to _the last merge commit on the `GITHUB_REF` branch_. At first, I would expect that it refers to the last commit of the branch. I wanted to use this behaviour for tagging container images build from PR events.

`github-slug-action` **is actually working as intended.**

**Describe the solution you'd like**

I would like to have a way of telling `github-slug-action` that I want to get the value of the last commit of my branch instead the logic used by GitHub.

Here's some track to get us started:
- https://github.community/t/github-sha-not-the-same-as-the-triggering-commit/18286/2
- https://github.community/t/github-sha-but-how-to-get-the-latest-commit-reference-on-a-branch/17160

I did not try those solutions yet.

**Describe alternatives you've considered**

/

**Additional context**

/

WDYT?

**Comment by rlespinasse** [comment]
The goal of this github action is to expose slug/short version of existing environment variables.

**Comment by rlespinasse** [comment]
The goal of this github action is to expose slug/short version of existing environment variables.

To go with this philosophy, I think we can expose this kind of information, the same way we have done it for `GITHUB_EVENT_REF_SLUG/GITHUB_EVENT_REF_SLUG_URL`.

In this case, the possible solution will be to load a new environment variable `GITHUB_EVENT_PULL_REQUEST_HEAD_SHA_SHORT` in case of present of `github.event.pull_request.head.sha`.

**Comment by MadJlzz** [comment]
It's my first time developing a github action but it does not bother me trying. May I try with what you said?

**Comment by rlespinasse** [comment]
@MadJlzz 👍 Go for it

**Comment by rlespinasse** [comment]
Thanks @MadJlzz for your contribution
