### ISSUE TITLE
Warning for breaking changes

### ISSUE THREAD

**Issue by Fryuni** [rlespinasse/github-slug-action#55]
This change [here](https://github.com/rlespinasse/github-slug-action/commit/78985f84eca97ef1c5262e85e8a73a277494c4ed) breaks every workflow that used the `GITHUB_REF_SLUG` on services that require slugs starting with a letter.

Before it was guaranteed to have a value like `refs-pull-<pr number>-merge` and now it is `<pr number>-merge`.  
Took us a while to find why our staging deployments suddenly stopped working. Could that be added to the release notes so others will find it more quickly?

**Comment by rlespinasse** [comment]
I will fix it to keep `pull-<pr number>-merge` part and document it.

In addition, @Fryuni Can you tell me more about your use case? maybe we need to do more.

**Comment by Fryuni** [comment]
We use the slug as a revision tag on Google Cloud Run to get a url for the PR. It has a character limit that is too low for us to use the branch name, but using the ref slug works fine.

**Comment by rlespinasse** [comment]
Thanks for the explanation,
I will finally revert the breaking change, open a bug (which I have forget to do 😄 the first time) and take time to find a proper solution.

**Comment by Fryuni** [comment]
I think the behavior you changed to is the correct one. I was using something that was technically unintentional. Solved it easily by prefixing `pr-` to the tag.

I would just document the change on the release notes

**Comment by rlespinasse** [comment]
@Fryuni will do

**Comment by rlespinasse** [comment]
In addition to the related PR, the release notes have been updated https://github.com/rlespinasse/github-slug-action/releases/tag/3.3.0
