### ISSUE TITLE
underscore (_) in branch name is replaced with dash (-)

### ISSUE THREAD

**Issue by TSMMark** [rlespinasse/github-slug-action#62]
**Describe the bug**
see issue title

**To Reproduce**
print the env vars and see that the branch name has dashes instead of underscores

**Expected behavior**
The env var should include the actual branch name, not replace any characters.

**Screenshots**
<img width="411" alt="Screen Shot 2021-03-30 at 11 22 07 AM" src="https://user-images.githubusercontent.com/4197823/113014789-e5909f80-914a-11eb-94a2-092e33556b5a.png">

**Additional context**
Thanks for the really useful package!

**Comment by rlespinasse** [comment]
Make sense for `_SLUG` variables.
For `_SLUG_URL` variables, the current rules will remain the same.

**Comment by TSMMark** [comment]
I could send a PR if you point me to which lines to update and what specs + doc updates you would need

**Comment by rlespinasse** [comment]
The rules are in this section : https://github.com/rlespinasse/github-slug-action#overview
The implementation is defined on https://github.com/rlespinasse/github-slug-action/blob/v3.x/src/slug.ts
The test suites are in : 
- https://github.com/rlespinasse/github-slug-action/blob/v3.x/__tests__/slug.test.ts
- https://github.com/rlespinasse/github-slug-action/blob/v3.x/__tests__/slugref.test.ts

**Comment by TSMMark** [comment]
So I will at minimum be updating this test case:

https://github.com/rlespinasse/github-slug-action/blob/6c93fcbf53da9c6415bd7f5e37579b488f34339e/__tests__/slugref.test.ts#L38-L41

Are we concerned about changing this and possibly breaking users' workflows? Or you think if they're specifying the action version properly we could rely on semantic versioning and release a major version and be okay?

**Comment by rlespinasse** [comment]
I see this change as a new feature, not a breaking change. 
That also why the `_SLUG_URL` is not impacted by this change.
This will act as minor version on semantic versioning level.
