### ISSUE TITLE
Get current branch even on tag event

### ISSUE THREAD

**Issue by Ameausoone** [rlespinasse/github-slug-action#79]
**Is your feature request related to a problem? Please describe.**
It could be useful to get current branch, even when pipeline has been triggered by a tag event.

**Describe the solution you'd like**
Get a variable which provide current branch.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rlespinasse** [comment]
@Ameausoone can you tell me more about a use case for this feature?

On GitHub Actions, event triggers are often based on a git branch (the default one or not). When the git tag is the trigger of the event, the associated git branch (ask by this feature) can be more than just one git branch.
