### ISSUE TITLE
 multiple - character are removed

### ISSUE THREAD

**Issue by jdlmf** [rlespinasse/github-slug-action#94]
**Describe the bug**
SLUG on a variable remove double - character, this behavior is not in the documentation.

**Comment by rlespinasse** [comment]
After verification, this bug was present from the beginning except on `v3` series.
After the fix, the default behavior of `v4` will be the documented one (and the same as `v3`).
Input will be added to enable the user to reproduce the current behavior where all `--` are reduced to `-`)
